-- DDL for Consultancy Data Engineering Sandbox
-- Two environments: production and development

CREATE OR REPLACE DATABASE CONSULTANCY_PROD;
CREATE OR REPLACE DATABASE CONSULTANCY_DEV;

USE DATABASE CONSULTANCY_PROD;

CREATE SCHEMA IF NOT EXISTS RAW_SOURCE;
CREATE SCHEMA IF NOT EXISTS SOURCE_TRANSFORMED;
CREATE SCHEMA IF NOT EXISTS CORE_BUSN_ENTITY;
CREATE SCHEMA IF NOT EXISTS CORE_REPORTING;

USE DATABASE CONSULTANCY_DEV;

CREATE SCHEMA IF NOT EXISTS RAW_SOURCE;
CREATE SCHEMA IF NOT EXISTS SOURCE_TRANSFORMED;
CREATE SCHEMA IF NOT EXISTS CORE_BUSN_ENTITY;
CREATE SCHEMA IF NOT EXISTS CORE_REPORTING;

-- Suggested layer naming:
-- RAW_SOURCE -> source ingestion layer
-- STAGE      -> transformed / intermediate layer
-- CORE       -> business entity / operational models
-- DIM_FACT   -> dimensional and fact models
