
-- Tell Snowflake to use this new database


-- DROP TABLE IF EXISTS PUBLIC.RAW_SOURCE_EMPL_PERS;

-- USE DATABASE CONSULTANCY_DEV;
-- USE SCHEMA RAW_SOURCE;

-- -- TASK 1: Create the Source Table
-- CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_PERS 
-- (
--     EMPL_PERS_ID NUMBER PRIMARY KEY,
--     EMPL_PERS_FNM VARCHAR NOT NULL,
--     EMPL_PERS_LNM VARCHAR NOT NULL,
--     EMPL_PERS_DOB DATE NOT NULL,
--     EMPL_PERS_GENCD VARCHAR(1),
--     EMPL_PERS_EMAILP VARCHAR,
--     EMPL_PERS_EMAILW VARCHAR NOT NULL,
--     EMPL_PERS_MOBP VARCHAR(15) NOT NULL,
--     EMPL_PERS_MOBW VARCHAR(15) NOT NULL
-- );

-- -- TASK 2: Insert 3 Sample Records
-- INSERT INTO CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_PERS (
--     EMPL_PERS_ID, EMPL_PERS_FNM, EMPL_PERS_LNM, EMPL_PERS_DOB, 
--     EMPL_PERS_GENCD, EMPL_PERS_EMAILP, EMPL_PERS_EMAILW, EMPL_PERS_MOBP, EMPL_PERS_MOBW
-- ) VALUES 
-- (1, 'John', 'Doe', '1990-05-15', 'M', 'john.doe.private@gmail.com', 'john.doe@company.com', '+61415550191', '+61415550192'),
-- (2, 'Jane', 'Smith', '1992-08-22', 'F', 'jane.s@yahoo.com', 'jane.smith@company.com', '+61415550193', '+61415550194'),
-- (3, 'Alex', 'Jones', '1988-12-01', 'X', NULL, 'alex.jones@company.com', '+61415550195', '+61415550196');

-- Practice SELECT statement to see your data
SELECT * FROM CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_PERS;

UPDATE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_PERS
SET EMPL_PERS_EMAILW = REPLACE(EMPL_PERS_EMAILW, 'company.com', 
'sandyconsulting.com.au')
WHERE EMPL_PERS_EMAILW LIKE '%company.com'
;