USE DATABASE CONSULTANCY_DEV;
USE SCHEMA RAW_SOURCE;

-- Drop dependent tables first to clear previous relationships safely
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_ADDR;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_ACC;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_CAR;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_EMPL_CAR_WRONG; -- Cleans up old wrong table
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_ENG;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_TMST;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_INV;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_INS;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_BILL;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_PERS;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_CLNT_ACC;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_OTRN;
DROP TABLE IF EXISTS CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_CLNT_PERS;

-- 12. Employee Personal
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_PERS (
    EMPL_PERS_EID NUMBER PRIMARY KEY,
    EMPL_PERS_FNM VARCHAR NOT NULL,
    EMPL_PERS_LNM VARCHAR NOT NULL,
    EMPL_PERS_DOB DATE NOT NULL,
    EMPL_PERS_GENCD VARCHAR(1),
    EMPL_PERS_EMAILP VARCHAR,
    EMPL_PERS_EMAILW VARCHAR NOT NULL,
    EMPL_PERS_MOBP VARCHAR(15) NOT NULL,
    EMPL_PERS_MOBW VARCHAR(15) NOT NULL
);

-- 1. Employee Address
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_ADDR (
    EMPL_ADDR_EID NUMBER PRIMARY KEY,
    EMPL_ADDR_LN1 VARCHAR NOT NULL,
    EMPL_ADDR_LN2 VARCHAR,
    EMPL_ADDR_SUBRB VARCHAR NOT NULL,
    EMPL_ADDR_CITY VARCHAR NOT NULL,
    EMPL_ADDR_STATECD VARCHAR(10) NOT NULL,
    EMPL_ADDR_POSTCD VARCHAR(10) NOT NULL,
    EMPL_ADDR_CNTRYCD VARCHAR(3) NOT NULL,
    EMPL_ADDR_RESFLG VARCHAR(1) NOT NULL,
    EMPL_ADDR_BUSNFLG VARCHAR(1) NOT NULL--,
    --FOREIGN KEY (EMPL_ADDR_EID) REFERENCES CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_PERS(EMPL_PERS_EID)
);

-- 2. Employee Account
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_ACC (
    EMPL_ACC_EAID NUMBER PRIMARY KEY,
    EMPL_ACC_EID NUMBER NOT NULL,
    EMPL_ACC_JONDAT DATE NOT NULL,
    EMPL_ACC_CRDAT TIMESTAMP_NTZ NOT NULL,
    EMPL_ACC_TDAT DATE,
    EMPL_ACC_STA VARCHAR(10) NOT NULL,
    EMPL_ACC_TYPE VARCHAR(20) NOT NULL,
    FOREIGN KEY (EMPL_ACC_EID) REFERENCES RAW_SOURCE_EMPL_PERS(EMPL_PERS_EID)
);

-- 3. Employee Career (Fixed Naming Prefix Here)
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_CAR (
    EMPL_CAR_EAID NUMBER PRIMARY KEY,
    EMPL_CAR_ROLE VARCHAR NOT NULL,
    EMPL_CAR_STDAT DATE NOT NULL,
    EMPL_CAR_RELSTDAT DATE,
    EMPL_CAR_TRNFLG VARCHAR(1) NOT NULL,
    FOREIGN KEY (EMPL_CAR_EAID) REFERENCES RAW_SOURCE_EMPL_PERS(EMPL_PERS_EID)
);

-- 4. Client Personal
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_CLNT_PERS (
    CLNT_PERS_CID NUMBER PRIMARY KEY,
    CLNT_PERS_RNAME VARCHAR NOT NULL,
    CLNT_PERS_ABN VARCHAR(20) NOT NULL,
    CLNT_PERS_IND VARCHAR NOT NULL,
    CLNT_PERS_PORT VARCHAR NOT NULL,
    CLNT_PERS_EMAIL VARCHAR NOT NULL,
    CLNT_PERS_MOB VARCHAR(15) NOT NULL,
    CLNT_PERS_WEBSITE VARCHAR,
    CLNT_PERS_ADDRLN1 VARCHAR NOT NULL,
    CLNT_PERS_ADDRLN2 VARCHAR,
    CLNT_PERS_SUBRB VARCHAR NOT NULL,
    CLNT_PERS_CITY VARCHAR NOT NULL,
    CLNT_PERS_STATECD VARCHAR(10) NOT NULL,
    CLNT_PERS_POSTCD VARCHAR(10) NOT NULL,
    CLNT_PERS_CNTRYCD VARCHAR(3) NOT NULL,
    CLNT_PERS_MGRID NUMBER
);

-- 5. Client Account
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_CLNT_ACC (
    CLNT_ACC_CAID NUMBER PRIMARY KEY,
    CLNT_ACC_CID NUMBER NOT NULL,
    CLNT_ACC_ENGDT DATE NOT NULL,
    CLNT_ACC_CRDAT TIMESTAMP_NTZ NOT NULL,
    CLNT_ACC_TDAT DATE,
    CLNT_ACC_STA VARCHAR(10) NOT NULL,
    CLNT_ACC_TYPE VARCHAR(20) NOT NULL,
    FOREIGN KEY (CLNT_ACC_CID) REFERENCES RAW_SOURCE_CLNT_PERS(CLNT_PERS_CID)
);

-- 6. Employee Engagement
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_ENG (
    EMPL_ENG_EAID NUMBER NOT NULL,
    EMPL_ENG_CAID NUMBER NOT NULL,
    EMPL_ENG_CONSTDAT DATE NOT NULL,
    EMPL_ENG_CONENDAT DATE,
    EMPL_ENG_CLNT_MGRID NUMBER NOT NULL,
    PRIMARY KEY (EMPL_ENG_EAID, EMPL_ENG_CAID),
    FOREIGN KEY (EMPL_ENG_EAID) REFERENCES CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_PERS(EMPL_PERS_EID),
    FOREIGN KEY (EMPL_ENG_CAID) REFERENCES CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_CLNT_ACC(CLNT_ACC_CAID)
);

-- 7. Timesheet
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_TMST (
    TMST_ID NUMBER PRIMARY KEY,
    TMST_EAID NUMBER NOT NULL,
    TMST_TRNID VARCHAR(50) NOT NULL,
    TMST_DAT DATE NOT NULL,
    TMST_WRKHRS NUMBER(5,2) NOT NULL,
    TMST_BILHRS NUMBER(5,2) NOT NULL,
    TMST_STATUS VARCHAR(20) NOT NULL,
    TMST_ACCTYPE VARCHAR(20) NOT NULL,
    FOREIGN KEY (TMST_EAID) REFERENCES RAW_SOURCE_EMPL_PERS(EMPL_PERS_EID)
);

-- 8. Employee Investment (Newly Included Table)
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_INV (
    EMPL_INV_EAID NUMBER PRIMARY KEY,
    EMPL_INV_TYPE VARCHAR(50) NOT NULL,
    EMPL_INV_PCT NUMBER(5,2) NOT NULL,
    EMPL_INV_TERM NUMBER NOT NULL,
    EMPL_INV_GUARAMT NUMBER(12,2) NOT NULL,
    FOREIGN KEY (EMPL_INV_EAID) REFERENCES CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_PERS(EMPL_PERS_EID)
);

-- 9. Employee Insurance
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_INS (
    EMPL_INS_EAID NUMBER PRIMARY KEY,
    EMPL_INS_TYPE VARCHAR(50) NOT NULL,
    EMPL_INS_PCT NUMBER(5,2) NOT NULL,
    EMPL_INS_COVER NUMBER(12,2) NOT NULL,
    EMPL_INS_PREM NUMBER(10,2) NOT NULL,
    FOREIGN KEY (EMPL_INS_EAID) REFERENCES RAW_SOURCE_EMPL_PERS(EMPL_PERS_EID)
);

-- 10. Employee Billing
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_EMPL_BILL (
    EMPL_BILL_ID NUMBER PRIMARY KEY,
    EMPL_BILL_TRNTYP VARCHAR(20) NOT NULL,
    EMPL_BILL_PRICTYPE VARCHAR(20) NOT NULL,
    EMPL_BILL_UNITTYPE VARCHAR(20) NOT NULL,
    EMPL_BILL_VALUE NUMBER(10,2) NOT NULL,
    EMPL_BILL_STDAT DATE NOT NULL,
    EMPL_BILL_ENDAT DATE
);

-- 11. Transaction
CREATE OR REPLACE TABLE CONSULTANCY_DEV.RAW_SOURCE.RAW_SOURCE_OTRN (
    OTRN_ID NUMBER PRIMARY KEY,
    OTRN_PYRAID NUMBER NOT NULL,
    OTRN_PYEAID NUMBER NOT NULL,
    OTRN_TRNTYP VARCHAR(20) NOT NULL,
    OTRN_TRNSTA VARCHAR(20) NOT NULL,
    OTRN_TRNAMT NUMBER(18,2) NOT NULL,
    OTRN_TRNSEQ NUMBER NOT NULL
);


SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'RAW_SOURCE'
AND TABLE_CATALOG = 'CONSULTANCY_DEV'
ORDER BY ORDINAL_POSITION;